## Charlotte USGS Flow Files
This collection of scripts imports IDA and NWIS data files into site
specific .rds files for Charlotte streams.

### ida2007.r
This is a collection of code snippets to import and format text files
downloaded from the IDA website.  There is a lot of hardcoding of
paths and file names, but this all should only need to be run one
time.  All updating is done through the more user friendly NWIS.

This code is a bit longer because IDA data swithces from Standard to
EDT time on 10-01-2005.

### idaNWISCombine.r
This is another collection of site specific code snippets to pull data
up to present (24 May 2017) from NWIS using dataRetrieval, and then
format and rbind those data onto the ida files generated by
ida2007.r.  These NWIS calls (2007-2017) take a little while to run,
but this is also a one time use file.

### updateFlowFiles.r
This file opens the "mostly current" .rds files generated by
idaNWISCombine.r, and then does NWIS calls to pull any newer data
(e.g., the past week or month) and rbind and save that.  Thus, going
forward, this should be the only file that needs to be run to keep the
site specific USGS .rds files up to date, and it runs fairly quickly
(i.e., minutes).

### aggregateHourly.r
This files runs over the complete .rds flow files and computes hourly
flow rates from the 15 minute records.  This cuts the file size
substantially, and makes for more responsive Shiny apps.
